// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCITogFHqdI9SWjNO9iJm8k6bK36vKXWQQ',
    appId: '1:742877783320:web:8d895b2b4ddac825cdaa6d',
    messagingSenderId: '742877783320',
    projectId: 'shopiee-93a6b',
    authDomain: 'shopiee-93a6b.firebaseapp.com',
    storageBucket: 'shopiee-93a6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYHHm9ZnfFOqJXtJULWkMBvZ017X0nMrY',
    appId: '1:742877783320:android:5fc9f8b1fe9eb560cdaa6d',
    messagingSenderId: '742877783320',
    projectId: 'shopiee-93a6b',
    storageBucket: 'shopiee-93a6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_nFRr8A6EpJtjV9nyUmKrLVb0pIV5em4',
    appId: '1:742877783320:ios:c656761cbf06f933cdaa6d',
    messagingSenderId: '742877783320',
    projectId: 'shopiee-93a6b',
    storageBucket: 'shopiee-93a6b.appspot.com',
    iosBundleId: 'com.example.shopiee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_nFRr8A6EpJtjV9nyUmKrLVb0pIV5em4',
    appId: '1:742877783320:ios:c656761cbf06f933cdaa6d',
    messagingSenderId: '742877783320',
    projectId: 'shopiee-93a6b',
    storageBucket: 'shopiee-93a6b.appspot.com',
    iosBundleId: 'com.example.shopiee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCITogFHqdI9SWjNO9iJm8k6bK36vKXWQQ',
    appId: '1:742877783320:web:eabaec3918ca4f82cdaa6d',
    messagingSenderId: '742877783320',
    projectId: 'shopiee-93a6b',
    authDomain: 'shopiee-93a6b.firebaseapp.com',
    storageBucket: 'shopiee-93a6b.appspot.com',
  );
}
